### ISSUE TITLE
Add support for Intercom events

### ISSUE THREAD

**Issue by jahunt1** [busybusy/AnalyticsKit-Android#3]
Reference: [Track events in Intercom](https://docs.intercom.com/the-intercom-platform/track-events-in-intercom)

**Comment by jahunt1** [comment]
Oops! I forgot I already did this in #2.

**Comment by ahmedrem55538** [comment]
> Reference: [Track events in Intercom](https://docs.intercom.com/the-intercom-platform/track-events-in-intercom)

rem55538@aljdie.com

**Comment by ahmedrem55538** [comment]
#11
