### ISSUE TITLE
Update default branch to 'main'

### ISSUE THREAD

**Issue by jahunt1** [busybusy/AnalyticsKit-Android#42]
To be consistent with GitHub standards, we should change the default branch name to `main` instead of `master`. 

@simon-the-canadian I am planning on doing this later this week - let me know if I should hold off since all forks will need to update the default branch to `main` as well.

**Comment by simon-the-canadian** [comment]
@jahunt1 Go ahead, it won't cause any issues.

**Comment by jahunt1** [comment]
@simon-the-canadian I'll need your help with the back half of this one. I pushed the new `main` branch, but I don't have permission to change the default branch on the busybusy repo or delete the old `master` branch. 

Would you mind finishing this for me please? GitHub has some simple instructions for [Changing the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch). Just a heads up - when I did this on my local fork I had to go to the repo settings and "Disable branch protection" to be able to change the default branch and delete `master`. After I did that I re-enabled branch protection from the repo settings.
